platform :ios, '13.0'

target 'Didit360' do
  use_frameworks!
  
  # NativeScript Pods
  pod 'NativeScript', :path => '../node_modules/@nativescript/core'
  
  # Additional dependencies
  pod 'SDWebImage'
  pod 'SwiftKeychainWrapper'
  pod 'IQKeyboardManagerSwift'
  
  # Analytics and Crash Reporting
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  
  # Social Authentication
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  
  # Media handling
  pod 'AVFoundation'
  pod 'AudioKit'
  
  # Biometrics
  pod 'LocalAuthentication'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end